services:    
  native_php:
    build: .
    container_name: native_php
    image: native_php
    restart: always
    volumes:
      - .:/var/www/html/native_php
    ports:
      - 3008:80
      - 5175:5173
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - mysql_database

networks:
  mysql_database:
    external: true